#!/usr/bin/env bash
# coding=utf-8

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_file' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

# Needed for both starting the service and building the docs.
# Gets set in .github/settings.yml, but doesn't seem to inherited by
# this script.
export DJANGO_SETTINGS_MODULE="pulpcore.app.settings"
export PULP_SETTINGS="$PWD/.ci/ansible/settings/settings.py"
export PULP_URL="http://pulp"

./generate.sh pulpcore python
pip install ./pulpcore-client
./generate.sh pulp_file python
pip install ./pulp_file-client

python .github/workflows/scripts/test_bindings.py

rm -rf ./pulpcore-client
./generate.sh pulpcore ruby
pushd pulpcore-client
  gem build pulpcore_client
  gem install --both ./pulpcore_client-*.gem
popd

rm -rf ./pulp_file-client
./generate.sh pulp_file ruby
pushd pulp_file-client
gem build pulp_file_client
gem install --both ./pulp_file_client-*.gem
popd

ruby .github/workflows/scripts/test_bindings.rb
